CREATE TABLE Nhanvien(
    MANV INT NOT NULL PRIMARY KEY,
    HOTEN VARCHAR(50) NOT NULL ,
    PHAI VARCHAR(50),
    NGAYSINH DATE,
    DIACHI VARCHAR(255),
    SDT VARCHAR(10)
    ) 
CREATE TAB LE KHÁCH_HÀNG(
    MAKH INT  IDENTITY(100,5) NOT NULL PRIMARY KEY,
    TENKH VARCHAR (50) NOT NULL,
    DIACHI VARCHAR(255),
    SDT VARCHAR (10) CHECK (SDT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)
ALTER TABLE NHANVIEN 
ADD EMAIL VARCHAR(100)
ALTER TABLE NHANVIEN
ALTER COLUMN DIACHI VARCHAR(100) 

ALTER TABLE NHANVIEN
ADD CONSTRAINT   NGAYSINHCHECK CHECK(NGAYSINH <=GETDATE())


TRUNCATE TABLE NHANVIEN
DROP TABLE KHÁCH_HÀNG

 CREATE TABLE SINHVIEN (
       MASV INT PRIMARY KEY NOT NULL,
       HOTEN VARCHAR (50) NOT NULL,
       LOP VARCHAR(20),
       NGANH VARCHAR(20),
       DIEMTB FLOAT
 )

 ALTER TABLE SINHVIEN 
 ADD EMAILSV VARCHAR(100)
     

 ALTER TABLE SINHVIEN 
 ALTER COLUMN DIEMTB DECIMAL(2,1)

 ALTER TABLE SINHVIEN
 DROP COLUMN NGANH

 ALTER TABLE SINHVIEN 
 ADD CONSTRAINT DIEMTBCHECK CHECK (DIEMTB>=0)

 ALTER TABLE SINHVIEN
 ADD
