CREATE DATABASE CSDL_THI_CONG
GO
USE CSDL_THI_CONG


-- TẠO BẢNG HÀNG
CREATE TABLE HANG(
       HangCN int NOT NULL CHECK(HangCN BETWEEN 1 AND 5),
       HeSoLuong decimal(3,1) NOT NULL,
       CONSTRAINT KC_HANG primary key(HangCN)
);
-- TẠO BẢNG CÔNG NHÂN
CREATE TABLE CONGNHAN(
       MaCN int NOT NULL,
       Ho varchar(30) NOT NULL,
       Ten varchar(15) NOT NULL,
       NgaySinh date,
       GioiTinh char check(GioiTinh in('f','F','M','m')),
       HangCN int NOT NULL CHECK(HangCN BETWEEN 1 AND 5),
       NgayTuyenDung date,
       MaDoi int NOT NULL,
       CONSTRAINT KC_CONGNHAN primary key(MaCN)
);
-- TẠO BẢNG ĐỘI THI CÔNG
CREATE TABLE DOITHICONG(
       MaDoi int NOT NULL,
       DoiTruong int,
       ThuocDonVi int NOT NULL,
       CONSTRAINT KC_THICONG primary key(MaDoi)
);
-- TẠO BẢNG CÔNG TRÌNH
CREATE TABLE CONGTRINH(
       MaCT int NOT NULL,
       TenCT varchar(50) NOT NULL,
       DiaDiem varchar(50),
       DonViChinh int NOT NULL,
       CONSTRAINT KC_CONGTRINH primary key(MaCT)
);
-- TẠO BẢNG CHẤM CÔNG
CREATE TABLE CHAMCONG(
       MaCT int NOT NULL,
       MaDoi int NOT NULL,
       MaCN int NOT NULL,
       NgayLamViec date NOT NULL,
       SoGio float NOT NULL,
       CONSTRAINT KC_CHAMCONG primary key(MaCT,MaDoi,MaCN,NgayLamViec)
);

-- TẠO KHÓA NGOẠI BẢNG CÔNG NHÂN

ALTER TABLE CONGNHAN
ADD CONSTRAINT CONGNHAN_HANG FOREIGN KEY (HangCN) REFERENCES HANG(HangCN),
    CONSTRAINT CONGNHAN_DOITHICONG FOREIGN KEY (MaDoi) REFERENCES DOITHICONG(MaDoi);


-- TẠO KHÓA NGOẠI BẢNG DOITHICONG
ALTER TABLE DOITHICONG
ADD CONSTRAINT DOITHICONG_CONGNHAN FOREIGN KEY (DoiTruong) REFERENCES CONGNHAN(MaCN);

-- TẠO KHÓA NGOẠI BẢNG CHAMCONG
ALTER TABLE CHAMCONG
ADD CONSTRAINT CHAMCONG_CONGTRINH FOREIGN KEY (MaCT) REFERENCES CONGTRINH(MaCT),
    CONSTRAINT CHAMCONG_DOITHICONG FOREIGN KEY (MaDoi) REFERENCES DOITHICONG(MaDoi),
    CONSTRAINT CHAMCONG_CONGNHAN FOREIGN KEY (MaCN) REFERENCES CONGNHAN(MaCN);


--- TẮT HẾT KHÓA NGOẠI
ALTER TABLE CONGNHAN NOCHECK CONSTRAINT ALL;
ALTER TABLE DOITHICONG NOCHECK CONSTRAINT ALL;
ALTER TABLE CHAMCONG NOCHECK CONSTRAINT ALL;


--- THÊM DỮ LIỆU
INSERT INTO HANG
VALUES (1,3.0),
       (2,3.5),
       (3,4.0),
       (4,4.5),
       (5,5.0);


INSERT INTO DOITHICONG
VALUES (1,null,10),
       (2,null,20);

INSERT INTO CONGNHAN
VALUES (118,'Tran Van','Hung','2000-08-15','M',1,'2023-11-01',1),
       (138,'Nguyen','Khanh','1995-04-23','M',3,'2021-03-01',2);

INSERT INTO CONGTRINH
VALUES (11,'Nha o Tran Thai Binh','Quan 3',10),
       (12,'Van phong HBC','Quan 7',20);

INSERT INTO CHAMCONG
VALUES (11,1,118,'2024-03-11',8.0),
       (12,2,138,'2024-04-05',8.0);

-- MỞ KHÓA NGOẠI
ALTER TABLE CONGNHAN CHECK CONSTRAINT ALL;
ALTER TABLE DOITHICONG CHECK CONSTRAINT ALL;
ALTER TABLE CHAMCONG CHECK CONSTRAINT ALL;


