--- TẠO CSDL
CREATE DATABASE CSDL_TAXI
GO
USE CSDL_TAXI

--- TẠO BẢNG LAXIE
CREATE TABLE LAIXE(
       MaLX int NOT NULL,
       Ho varchar(15) NOT NULL,
       Dem varchar(15) ,
       Ten varchar(15) NOT NULL,
       NgaySinh date ,
       SoGP char(12) NOT NULL,
       HanGP date NOT NULL,
       
       CONSTRAINT LAIXE_KHOACHINH PRIMARY KEY (MaLX)
);

--- TẠO LOẠI PHƯƠNG TIỆN
CREATE TABLE LOAI_PHUONGTIEN(
       LoaiPT int NOT NULL,
       TenLoai varchar(64) NOT NULL, 

       CONSTRAINT LOAI_PTKHOAHCING PRIMARY KEY(LoaiPT)
);

--- TẠO PHƯƠNG TIỆN
CREATE TABLE PHUONGTIEN(
       LoaiPT int NOT NULL,
       SoPT int NOT NULL,
       BienSo char(10) NOT NULL,
       NamSanXuat int NOT NULL,
       ChuPT int ,
       TinhTrang char NOT NULL DEFAULT '1' check (TinhTrang in('0','1')),
       CONSTRAINT PTKHOACHINH PRIMARY KEY(SoPT)
);

 CREATE  TABLE CALAMVIEC(
       MaCLV int NOT NULL,
       MaLX int NOT NULL,
       SoPT int NOT NULL,
       BatDau datetime ,
       KetThuc datetime,

       CONSTRAINT CAKHOACHINH PRIMARY KEY (MaCLV)
);

-- TAO KHOA NGOAI CALAMVIEC->LAXIE
ALTER TABLE CALAMVIEC
ADD CONSTRAINT CALAMVIEC_LAIXE FOREIGN KEY ( MaLX) REFERENCES LAIXE(MaLX);
-- TAO KHOA NGOAI PHUONGTIEN>LAXIE
ALTER TABLE PHUONGTIEN
ADD CONSTRAINT PHUONGTIEN_LAIXE FOREIGN KEY (ChuPT) REFERENCES LAIXE(MaLX);
-- TAO KHOA NGOAI CALAMVIEC->PHUONGTIEN
ALTER TABLE CALAMVIEC
ADD CONSTRAINT CALAMVIEC_PHUONGTIEN FOREIGN KEY (SoPT) REFERENCES PHUONGTIEN(SoPT);
-- TAO KHOA NGOAI PHUONGTIEN->LOAI_PHUONGTIEN
ALTER TABLE PHUONGTIEN
ADD CONSTRAINT PHUONGTIEN_LOAIPHUONGTIEN FOREIGN KEY (LoaiPT) REFERENCES LOAI_PHUONGTIEN(LoaiPT);

-- CHÈN DỮ LIỆU VÀO
--- TẮT HẾT KHÓA NGOẠI 
ALTER TABLE CALAMVIEC NOCHECK CONSTRAINT ALL;
ALTER TABLE PHUONGTIEN NOCHECK CONSTRAINT ALL;

--- THÊM DỮ LIỆU VÀO CỘT LAIXE
INSERT INTO LAIXE
VALUES (1,'Nguyen',	'Van','Tung','2000-1-15','799876543210','2030-7-5'),
       (2,'Le','Quoc','Huy', '1998-2-20','798765432109','2032-11-20');

-- THÊM DỮ LIỆU VÀO CỘT LOẠI PHƯƠNG TIỆN
INSERT INTO LOAI_PHUONGTIEN
VALUES (1,'Hatchback'),
       (2,'Sedan'),
       (3,'SUV');
       
-- THÊM DỮ LIỆU VÀO CỘT PHƯƠNG TIỆN 
INSERT INTO PHUONGTIEN
VALUES (2,1,'51E-135.75',2018,null,'1'),
       (3,2,'51E-482.36',2018,2,1);

-- THEEM DỮ LIỆU VÀO CỘT CA LÀM VIỆC
INSERT INTO CALAMVIEC
VALUES (1,1,1,'2023-1-1 8:00:00','2023-1-1 16:00:00'),
       (2,2,2,'2023-2-1 10:00:00','2023-2-1  18:00:00');

 -- BẬT KHÓA NGOẠI 

ALTER TABLE CALAMVIEC CHECK CONSTRAINT ALL;
ALTER TABLE PHUONGTIEN CHECK CONSTRAINT ALL;

